src/Entity/Commentary.php
<?php

namespace App\Entity;
use App\Entity\Service;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\CommentaryRepository;

/**
 * @ORM\Entity(repositoryClass=CommentaryRepository::class)
 */
class Commentary
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="commentaries")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\Column(type="text")
     */
    private $comment;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_At;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_At;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $deleted_At;

    /**
     * @ORM\ManyToOne(targetEntity=Service::class, inversedBy="commentaries")
     * @ORM\JoinColumn(nullable=false)
     */
    private $service;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_At;
    }

    public function setCreatedAt(\DateTimeInterface $created_At): self
    {
        $this->created_At = $created_At;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_At;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_At): self
    {
        $this->updated_At = $updated_At;

        return $this;
    }

    public function getDeletedAt(): ?\DateTimeInterface
    {
        return $this->deleted_At;
    }

    public function setDeletedAt(?\DateTimeInterface $deleted_At): self
    {
        $this->deleted_At = $deleted_At;

        return $this;
    }

    public function getService(): ?Service
    {
        return $this->service;
    }

    public function setService(?Service $service): self
    {
        $this->service = $service;

        return $this;
    }
    
}

src/Form/CommentaryType.php
<?php

namespace App\Form;

use App\Entity\User;
use App\Entity\Commentary;
use App\Entity\Service;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class CommentaryType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
        ->add('service', EntityType::class, [
            'class' => Service::class,
           'choice_label' => 'title',
           'label' => 'Choisissez un Coaching/Accompagnement'
   ])
        ->add('author', EntityType::class, [
            'class' => User::class,
            'choice_label' => 'lastname',
            'label' => 'Choisissez un Utilisateur'
        ])
        ->add('comment', TextareaType::class, [
            'label' => 'Commentez ici',
            'attr' => [
                'placeholder' => 'Commentez ici ce Coaching/Accompagnement'
            ],
            'constraints' => [
                new NotBlank([
                    'message' => 'Le commentaire ne peut être vide'
                ])
            ],
        ])
            // ->add('created_At')
            // ->add('updated_At')
            // ->add('deleted_At')

        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Commentary::class,
        ]);
    }
}

src/Controller/Admin/CommentaryController.php
<?php

namespace App\Controller\Admin;

use DateTime;
use App\Entity\Commentary;
use App\Entity\Service;
use App\Form\CommentaryType;
use App\Repository\CommentaryRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/admin/commentary")
 */
class CommentaryController extends AbstractController
{
    /**
     * @Route("/", name="app_commentary_index", methods={"GET"})
     */
    public function index(CommentaryRepository $commentaryRepository): Response
    {
        return $this->render('commentary/index.html.twig', [
            'commentaries' => $commentaryRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_commentary_new", methods={"GET", "POST"})
     */
    public function new(Request $request,Service $service, EntityManagerInterface $entityManager, CommentaryRepository $commentaryRepository): Response
    {
        $commentary = new Commentary();
        $form = $this->createForm(CommentaryType::class, $commentary);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $commentary->setService($service);
            $commentary->setCreatedAt(new DateTime());
            $commentary->setupdatedAt(new DateTime());

            $entityManager->persist($commentary);
            $entityManager->flush();

            $commentaryRepository->add($commentary);
            
            return $this->redirectToRoute('app_commentary_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('commentary/new.html.twig', [
            'commentary' => $commentary,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_commentary_show", methods={"GET"})
     */
    public function show(Commentary $commentary): Response
    {
        return $this->render('commentary/show.html.twig', [
            'commentary' => $commentary,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_commentary_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request,Service $service, Commentary $commentary,EntityManagerInterface $entityManager, CommentaryRepository $commentaryRepository): Response
    {
        $form = $this->createForm(CommentaryType::class, $commentary);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $commentary->setService($service);
            $commentary->setCreatedAt(new DateTime());
            $commentary->setupdatedAt(new DateTime());

            $entityManager->persist($commentary);
            $entityManager->flush();

            $commentaryRepository->add($commentary);
            return $this->redirectToRoute('app_commentary_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('commentary/edit.html.twig', [
            'commentary' => $commentary,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_commentary_delete", methods={"POST"})
     */
    public function delete(Request $request, Commentary $commentary, CommentaryRepository $commentaryRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$commentary->getId(), $request->request->get('_token'))) {
            $commentaryRepository->remove($commentary);
        }

        return $this->redirectToRoute('app_commentary_index', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/CommentariesController.php
<?php

namespace App\Controller;

use App\Entity\Commentary;
use App\Entity\Service;
use App\Form\CommentaryFormType;
use DateTime;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class CommentariesController extends AbstractController
{
    /**
     * @Route("ajouter-un-commentaire?/{category_title}/{service_title}_{id}", name="app_add_commentary", methods={"GET|POST"})
     */
    public function addCommentary(Service $service, Request $request, EntityManagerInterface $entityManager): Response
    {
        $commentary= new Commentary();

        $form =$this->createForm(CommentaryFormType::class, $commentary)->handleRequest($request);
       
        if($form->isSubmitted() && $form->isValid() === false ) {
            $this->addFlash('warning', 'Votre commentaire est vide !');

            return $this->redirectToRoute('app_show_service', [
                'category_title' => $service->getCategory()->getTitle(),
                'service_title' => $service->getTitle(),
                'id' => $service->getId()
            ]);
        } // endif

        if($form->isSubmitted() && $form->isValid()) { // === true
            
            $commentary->setService($service);
            $commentary->setCreatedAt(new DateTime());
            $commentary->setupdatedAt(new DateTime());

            $commentary->setAuthor($this->getUser());

            $entityManager->persist($commentary);
            $entityManager->flush();

            $this->addFlash('success', "Vous avez commenté le service <strong>". $service->getTitle() ." </strong> avec succès !");

            return $this->redirectToRoute('app_show_service', [
                'category_title' => $service->getCategory()->getTitle(),
                'service_title' => $service->getTitle(),
                'id' => $service->getId()
            ]);
        } // endif

        return $this->render('commentaries/new.html.twig', [
            // 'commentary' => $commentary,
            'form' => $form->createView()
        ]);

    } // End function addCommentary



} // End class CommentaryController

templates/commentary/_delete_form.html.twig
<form method="post" action="{{ path('app_commentary_delete', {'id': commentary.id}) }}" onsubmit="return confirm('Etes vous certain de vouloir supprimer définitivement ce Commentaire ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ commentary.id) }}">
    <button class="btn btn-danger"><i class="fa fa-trash fa-beat mx-2"></i>Supprimer</button>
</form>

templates/commentary/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <div class="col-1 mx-auto text-center">
        <button class="btn btn-warning" title="Sauvegarder"><i class="fa fa-edit fa-beat mx-2"></i>{{ button_label|default('Sauvegarder') }}</button>
    </div>
{{ form_end(form) }}

templates/commentary/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier le Commentaire{% endblock %}

{% block body %}
    <h1>Modifier le Commentaire</h1>
    <hr>
    {{ include('commentary/_form.html.twig', {'button_label': 'Sauvegarder'}) }}
    <hr>
    <div class="text-center mx-auto my-2">
        <p class="col-12"><a href="{{ path('app_commentary_index') }}" class="btn btn-view" title="Retour vers Liste"><i class="fa-solid fa-circle-arrow-left fa-beat mx-2"></i>Retour</a></p>
    </div>
    <hr>
    <div class="text-center mx-auto my-2">
        <h5 class="col-12">Supprimer le Commentaire*</h5>
        {{ include('commentary/_delete_form.html.twig') }}
        <p class="col-12">*Attention ! toute suppression est définitive.</p>
    </div>
    <hr>
{% endblock %}

templates/commentary/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gestion des Commentaires{% endblock %}

{% block body %}
    <h1>Gestion des Commentaires</h1>
    <table class="table">
        <thead>
            <tr>
                <th>Coaching</th>
                <th>Prénom</th>
                <th>Nom</th>
                <th>Contenu</th>
                <th>N°Id</th>
                <th>Crée le</th>
                <th>Modifié le</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for commentary in commentaries %}
            <tr>
                <td>{{ commentary.service.title }}</td>
                <td>{{ commentary.author.firstname }}</td>
                <td>{{ commentary.author.lastname }}</td>
                <td>{{ commentary.comment }}</td>
                <td>{{ commentary.id }}</td>
                <td>{{ commentary.createdAt ? commentary.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ commentary.updatedAt ? commentary.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_commentary_show', {'id': commentary.id}) }}" class="btn btn-info mt-2" title="Voir le commentaire"><i class="fa fa-magnifying-glass fa-beat mx-2"></i>Voir</a>
                    <form method="post" action="{{ path('app_commentary_delete', {'id': commentary.id}) }}" onsubmit="return confirm('Etes vous certain de vouloir supprimer ce Commentaire définitivement ?');">
                        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ commentary.id) }}">
                        <button class="btn btn-danger" title="Supprimer le Commentaire"><i class="fa fa-trash fa-beat mx-2"></i>Supprimer</button>
                    </form>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">Aucun Commentaire trouvé</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    
{% endblock %}

templates/commentary/new.html.twig
{# {% extends 'base.html.twig' %}

{% block title %}New Commentary{% endblock %}

{% block body %}
    <h1>Create new Commentary</h1>

    {{ include('commentary/_form.html.twig') }}

    <a href="{{ path('app_commentary_index') }}">back to list</a>
{% endblock %} #}

templates/commentary/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commentaire{% endblock %}

{% block body %}
    <h1>Commentaire</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Coaching</th>
                <td>{{ commentary.service.title }}</td>
            </tr>
            <tr>
                <th>Prénom</th>
                <td>{{ commentary.author.firstname }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ commentary.author.lastname }}</td>
            </tr>
            <tr>
                <th>Contenu</th>
                <td>{{ commentary.comment }}</td>
            </tr>
            <tr>
                <th>N°Id</th>
                <td>{{ commentary.id }}</td>
            </tr>
            <tr>
                <th>Crée le</th>
                <td>{{ commentary.createdAt ? commentary.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Modifié le</th>
                <td>{{ commentary.updatedAt ? commentary.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>
    
    <hr>
    <div class="text-center mx-auto my-2">
        <p class="col-12"><a href="{{ path('app_commentary_index') }}" class="btn btn-view" title="Retour vers Liste"><i class="fa-solid fa-circle-arrow-left fa-beat mx-2"></i>Retour</a></p>
    </div>
    <hr>
    <div class="text-center mx-auto my-2">
        <h5 class="col-12">Supprimer le Commentaire*</h5>
        {{ include('commentary/_delete_form.html.twig') }}
        <p class="col-12">*Attention ! toute suppression est définitive.</p>
    </div>
    <hr>
{% endblock %}